spring:
  application:
    name: prometheus-demo

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enable: true
    health:
      showDetails: always
  metrics:
    export:
      prometheus:
        enabled: true

server:
  port: 80



#management.server.port=8081
#management.endpoints.jmx.exposure.include=*
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always
#server.port=8080

